### ISSUE TITLE
[BUG] Artist tag refuses to download

### ISSUE THREAD

**Issue by BurningGryphon** [Official-Husko/NN-Downloader#30] opened 2024-05-04 13:39 UTC
More specifically, for some reason, it refuses to download anything by ConnivingRat off e621. I am on Win10.

1. Select E621
2. Type "connivingrat" and try to download any number of pages.
3. ???

**Screenshot:**
![image](https://github.com/Official-Husko/NN-Downloader/assets/104073537/a4d955e2-84f7-45e6-b305-90d800009847)

For some reason there is no log file with the program either so I can't find out the error either...

**Comment by Official-Husko** [comment] 2024-05-04 13:52
Investigating it right now.

**Comment by Official-Husko** [comment] 2024-05-04 14:07
After testing i can confirm that it works for me. Here is what you can try:

1. Make sure when pasting in the artists name there are no empty spaces at the front or back.
2. check your config to make sure its all setup correctly. double check your api key on e621.
3. check your blacklist on e6 and in the config.
4. make sure "safe mode" is disabled on your e6 account

If none of these things worked then we will have to try a few different things.

**Comment by BurningGryphon** [comment] 2024-05-04 14:24
Maybe I need to delete all of the db files and try again?

**Comment by BurningGryphon** [comment] 2024-05-04 14:33
Yep, doing that fixed the issue.

**Comment by Official-Husko** [comment] 2024-05-04 15:04
> Yep, doing that fixed the issue.

Deleting the database fixed the issue? Did you perhaps download all of the available images before? Or maybe the first 3 pages?

**Comment by Official-Husko** [comment] 2024-05-05 00:41
Closing the issue since it is resolved.

**Closed by Official-Husko** 2024-05-05 00:41 UTC
Labels: bug, enhancement
